web:    react-scripts start --color
node:   nodemon --config $root/nodemon.json --exec babel-node $src -- --config-file=$root/babel.config.js --no-babelrc | bunyan -o short --color
mongod: mkdir -p data/db && mongod --dbpath data/db --bind_ip 127.0.0.1 --port $PORT
redis:  redis-server --port $PORT

# These should never happen
foo1: echo foo1 && exit 1
foo2: echo foo2 && exit 1
foo3: echo foo3 && exit 1
foo4: echo foo4 && exit 1
foo5: echo foo5 && exit 1
