web:    cross-env PORT=`expr $PORT + $WEB_PORT_OFFSET` react-scripts start --color
node: cross-env PORT=`expr $PORT + $NODE_PORT_OFFSET` nodemon --config $root/nodemon.json --exec babel-node $src -- --config-file=$root/babel.config.js --no-babelrc
mongod: mkdir -p data/db && mongod --dbpath data/db --bind_ip 127.0.0.1 --port $MONGOD_PORT
redis:  redis-server --port $REDIS_PORT

# These should never happen
foo1: echo foo1 && exit 1
foo2: echo foo2 && exit 1
foo3: echo foo3 && exit 1
foo4: echo foo4 && exit 1
foo5: echo foo5 && exit 1
